// 1. Define and Export the Type
export type Experience = {
    id: number;
    title: string;
    company: string;
    logo: string;
    companyLogo: string;
    location: string;
    startDate: string;
    endDate: string;
    description: string[];
    summary: string;
    tags: string[];
};

export const experienceData = [
    {
        id: 1,
        title: "Member of Technical Staff",
        company: "Oracle",
        logo: "/images/education/oracle.png",
        companyLogo: "Oracle",
        location: "Denver, CO USA",
        startDate: "July 2025",
        endDate: "Present",
        description: [
            "Develop and maintain scalable software applications following architectural specifications and coding standards",
            "Troubleshoot and resolve moderately complex issues across development and production environments",
            " Collaborate cross-functionally with product, QA, and infrastructure teams to ensure high-quality releases",
            "Apply foundational to intermediate knowledge of software engineering principles in a fast-paced enterprise environment",
            "Participate in code reviews, design discussions, and contribute to continuous integration and delivery pipelines",
            "Gain exposure to Oracle’s internal tools, software lifecycle processes, and global engineering best practices",
        ],
        summary: "Architecting scalable solutions while streamlining continuous integration and global deployment workflows",
        tags: [
            "Oracle Cloud Infrastructure", 
            "OCI IoT", "Devops", "Careaware", 
            "HealthCare", 
            "GenAI", 
            "Automation", 
            "Kubernetes", 
            "Docker",
            "NextJs",
            "React.js",
            "TypeScript",
            "Java",
            "Git",
        ],
    },
    {
        id: 2,
        title: "Full Stack Developer Volunteer",
        company: "Saayam For All",
        logo: "/images/education/saayam.png",
        companyLogo: "Saayam For All",
        location: "Denver, CO USA",
        startDate: "Jan 2025",
        endDate: "July 2025",
        description: [
            "Refactored over 20,000 lines of React.js and React Native code to improve stability and reduce tech debt by 25%",
            "Debugged and optimized 20+ UI components, reducing resolution time by 35% and improving performance across mobile and web platforms",
            "Integrated RESTful APIs and managed state using Redux, enabling real-time data handling and responsive UI rendering",
            "Collaborated with QA and backend teams to ensure cross-browser compatibility, accessibility (a11y), and mobile responsiveness",
            "Implemented CI/CD pipelines using GitHub Actions, automating testing and deployment processes to streamline releases",
            "Enhanced user experience by redesigning navigation flows and optimizing load times, resulting in a 15% increase in user engagement",
        ],
        summary: "Enhanced application performance and stability by resolving technical debt and optimizing React component architecture",
        tags: [
            "Volunteering", 
            "ReactJs", 
            "NextJs", 
            "Redux",
            "Restful APIs",
            "Git",
            "Firebase",
        ],
    },
    {
        id: 3,
        title: "Teaching Assistant",
        company: "University of Colorado Denver",
        logo: "/images/education/cudenver.png",
        companyLogo: "CU",
        location: "Denver, CO USA",
        startDate: "Jan 2024",
        endDate: "May 2025",
        description: [
            "Mentored 40+ students in network programming, covering TCP/UDP sockets, multi-threaded communication, and real-time data transmission using C/C++",
            "Designed and graded lab assignments simulating client-server architectures and congestion control, increasing practical comprehension by 30%",
            "Supported 100+ students in mastering OOP fundamentals like inheritance, polymorphism, and encapsulation, improving exam performance and project quality",
            "Conducted weekly coding tutorials and 1:1 mentoring sessions focused on C++ class design, modular programming, and best practices in object-oriented design",
            "Assisted in developing course materials and lab exercises that enhanced students' hands-on experience with network programming concepts",
            "Provided feedback on student projects, emphasizing code efficiency, readability, and adherence to software development principles",
        ],
        summary: "Increased student comprehension by 30% through targeted mentorship in network protocols and software design patterns",
        tags: [
            "Education", 
            "Mentoring", 
            "Python", 
            "Java",
            "Object Oriented Programming",
            "C++",
            "Networking",
        ],
    },
    {
        id: 4,
        title: "Network Software Engineer",
        company: "Oracle Cerner",
        logo: "/images/education/oraclecerner.png",
        companyLogo: "Oracle",
        location: "Bengaluru, India",
        startDate: "Jun 2020",
        endDate: "Jul 2023",
        description: [
            "Delivered 24/7 NOC support for 13 hospitals, resolving 20+ critical incidents weekly and maintaining > 95% network uptime across 500+ Cisco and Alcatel devices.",
            "Configured and optimized 50+ VPN tunnels, 150+ ACL entries, and 10+ VLAN topologies, enhancing cross-site security and segmentation across enterprise networks",
            "Deployed and managed infrastructure using Cisco ASA, FMC, and Prime Infrastructure, reducing network downtime by 25% through proactive maintenance and monitoring",
            "Developed 3+ internal dashboard tools using React.js, JavaScript, and Chart.js to visualize live SNMP and NetFlow metrics, reducing triage time for on-call engineers by 20%",
            "Refactored legacy NOC UI tools with responsive design, lazy loading, and Webpack-based code splitting, improving load speed by 40% and reducing front-end errors by 25%",
            "Integrated REST APIs from SolarWinds and Cisco Prime to enable real-time updates for alert dashboards and firmware upgrade statuses, enhancing situational awareness for network operations teams",
            "Automated routine network tasks using Python and Shell scripts, cutting manual effort by 30% and accelerating incident response times",
            " Designed and implemented a firmware patching scheduler UI using React, Bootstrap, and REST APIs, resulting in 50% improvement in tracking accuracy for device upgrades",
            "Applied web accessibility (WCAG 2.1) standards and cross-browser compatibility updates, enhancing usability for a team of 25+ NOC engineers",
            "Authored 150+ SOPs, deployment playbooks, and troubleshooting guides, cutting new engineer onboarding time by 40% and improving team knowledge sharing",
            "Recognized with the NOTT (Night Owl Troubleshooter Team) Award – Q4 2022 for optimizing critical monitoring dashboards and resolving high-severity incidents under pressure",
        ],
        summary: "Bridging network operations and software development by building React dashboards and Python automation tools for enterprise infrastructure",
        tags: [
            "Oracle", 
            "Network", 
            "Automation", 
            "Healthcare",
            "NOC",
            "React.js",
            "Python",
            "Cisco",
        ],
    },
    {
        id: 5,
        title: "Software - System Intern",
        company: "Cerner",
        logo: "/images/education/cerner.png",
        companyLogo: "Cerner",
        location: "Bengaluru, India",
        startDate: "Jan 2020",
        endDate: "Jun 2020",
        description: [
            "Automated backup scheduling and compliance reporting using Python and SQL across 100+ servers, improving operational efficiency and reducing manual effort by 40%",
            "Provisioned and managed 30+ virtual machines via VMware and Hyper-V, enabling scalable infrastructure for internal development and reducing provisioning time by 35%",
            "Collaborated on the Remote Infrastructure Management (RIM) project, streamlining patch rollouts and backup monitoring for critical systems, contributing to 25% faster recovery during failures",
            "Developed PowerShell scripts to automate routine system administration tasks, cutting down manual workload by 30% and enhancing accuracy",
            "Monitored system performance and generated reports using Nagios and SolarWinds, identifying and resolving bottlenecks that improved system uptime by 15%",
            "Assisted in creating documentation for system configurations, backup procedures, and disaster recovery plans, enhancing team knowledge sharing and compliance",
        ],
        summary: "Streamlined critical system backups and virtual machine provisioning for scalable infrastructure",
        tags: [
            "Data Analytics", 
            "Healthcare", 
            "Real-time Systems",
            "Python",
            "PowerShell",
            "VMware",
            "System Administration",
        ],
    },
];
