export const experienceData = [
    {
        id: 1,
        title: "Member of Technical Staff",
        company: "Oracle",
        logo: "/images/education/corner-logo.png",
        companyLogo: "Oracle",
        location: "Denver, CO USA",
        startDate: "July 2025",
        endDate: "Present",
        description: "Worked on real-time data analytics for healthcare applications, improving data processing speeds.",
        tags: ["Data Analytics", "Healthcare", "Real-time Systems"],
    },
    {
        id: 2,
        title: "Teaching Assistant",
        company: "University of Colorado Denver",
        logo: "/images/education/du-logo.png",
        companyLogo: "CU",
        location: "Denver, CO USA",
        startDate: "Jan 2024",
        endDate: "May 2025",
        description: "Mentored students, graded assignments, and conducted tutorial sessions under Prof. Dave Ogle.",
        tags: ["Education", "Mentoring", "Python", "Java"],
    },
    {
        id: 3,
        title: "Network Software Engineer",
        company: "Oracle Cerner",
        logo: "/images/education/oracle-logo.png",
        companyLogo: "Oracle",
        location: "Bengaluru, India",
        startDate: "Jun 2020",
        endDate: "Jul 2023",
        description: "Developed and optimized software and network automation solutions for healthcare applications.",
        tags: ["Oracle", "Network", "Automation", "Healthcare"],
    },
    {
        id: 4,
        title: "Software - System Intern",
        company: "Cerner",
        logo: "/images/education/corner-logo.png",
        companyLogo: "Cerner",
        location: "Bengaluru, India",
        startDate: "Jan 2020",
        endDate: "Jun 2020",
        description: "Worked on real-time data analytics for healthcare applications, improving data processing speeds.",
        tags: ["Data Analytics", "Healthcare", "Real-time Systems"],
    },
];
